prooph_event_store:
    stores:
        tab_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore



services:
    _defaults:
        public: true
    Prooph\EventStore\Pdo\MySqlEventStore:
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

    Prooph\EventSourcing\Aggregate\AggregateType:
        factory: ['Prooph\EventSourcing\Aggregate\AggregateType', fromAggregateRootClass]
        arguments:
            $aggregateRootClass: Webbaard\Saloon\Domain\Tab\Tab
    Prooph\EventSourcing\Aggregate\AggregateTranslator: '@prooph_event_sourcing.aggregate_translator'
