prooph_service_bus:
    command_buses:
        tab_command_bus:
            router:
                type: 'prooph_service_bus.command_bus_router'
                routes:

    event_buses:
        tab_event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                type: 'prooph_service_bus.event_bus_router'

services:
    Prooph\ServiceBus\CommandBus: '@prooph_service_bus.tab_command_bus'
