framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'