page::home:
  path: /
  defaults: { _controller: Webbaard\Saloon\Application\Controller\HomepageController::indexAction }

data::tabs:
  path: /tabs/list.json
  defaults: { _controller: Webbaard\Saloon\Application\Controller\TabCollectionController::collectionAction }

data::menu:
  path: /menu/list.json
  defaults: { _controller: Webbaard\Saloon\Application\Controller\MenuCollectionController::collectionAction }

command::open-tab:
  path: /api/commands/open-tab
  defaults:
    _controller: Webbaard\Saloon\Application\Controller\ApiCommandController::postAction
    command_name: 'Webbaard\Saloon\Domain\Tab\Command\OpenTab'

data::tab:
  path: /tab/{id}.json
  defaults: { _controller: Webbaard\Saloon\Application\Controller\TabController::detailsAction }
